GET http://localhost:4004/odata/v4/book-store/Chapters
###
GET http://localhost:4004/odata/v4/book-store/Books
Authorization: Basic YWxpY2U6MTIz
###
GET http://localhost:4004/odata/v4/book-store/Books?$top=2
Authorization: Basic YWxpY2U6MTIz
###
POST http://localhost:4004/odata/v4/book-store/Books
Authorization: Basic YWxpY2U6MTIz
Content-Type: application/json

{
"ID":"8f7b6b2a-3f8d-4d5e-9c2b-1f3c6a9d2d15",
"title": "AMazing book about getting 1000 subscribers"
}